### ISSUE TITLE
How to transfer and apply to linear arrays？

### ISSUE THREAD

**Issue by SherryCatherine** [berkanlafci/pyoat#3]

**Comment by berkanlafci** [comment]
Dear @SherryCatherine,

Thanks for your question.

After you install pyoat package, you need to include the positions of your linear array transducers in your arrays folder. You need to use the same convention as in '.mat' files provided in the arrays folder (for example similar to 'ringCup.mat'). Then, you can choose your linear array in the example script by changing the 'cupType' variable with the name of your array position file.

Best regards,
Berkan
